# Generated by Django 5.2.6 on 2025-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('perfil', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=20)),
                ('papel', models.CharField(choices=[('usuario', 'Usuário'), ('moderador', 'Moderador'), ('admin', 'Admin')], default='usuario', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('localizacao', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('comprovante_residencia', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
            ],
        ),
    ]
